services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jword
    ports:
      - '5432:5432'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
