spring:
    application:
        name: J_word

    config:
        import: optional:file:.env[.properties]

    datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    mail:
        address: ${MAIL_SENDER}
        host: localhost
        port: 1025
        properties:
            "mail.host": localhost
            "mail.user": local
            "mail.smtp.auth": false
            "mail.smtp.starttls.enable": false
            "mail.smtp.localhost": localhost

jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
